Final-project
a-sheryshov/java-explore-with-me pull request #5
Opened 2023-07-14 16:59 UTC by a-sheryshov

feat: main_svc

2023-07-15 17:25 UTC, sergeymamonov requested changes
Если тесты не планируете делать, то лучше удалить папку test.

2023-07-15 17:25 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/event/mapper/EventMapper.java
> +    public static Event toEvent(EventRequestDto dto, Category category, Location location, User user) {
Этот метод где-то используется?

2023-07-15 17:25 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/event/service/EventAdminServiceImpl.java
> +        commonService.checkEventDate(dto, 1);
Число лучше выделить в константу и дать ей информативное название, которое показывало бы, какой смысл в этом числе.

2023-07-15 17:25 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/event/service/EventPrivateServiceImpl.java
> +        commonService.checkEventDate(dto, 2);
Число выделить в константу.

2023-07-15 17:25 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/event/service/EventPrivateServiceImpl.java
> +        }
Лучше делать ветку default на случай получения неподдержваемого статуса.

2023-07-15 17:25 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/event/service/EventPrivateServiceImpl.java
> +        if (event.getState().getName().equals(EventStates.PUBLISHED.name())) {
Метод equals необходимо вызывать у константы или у значения, которое гарантированно не равно null. Потому что если значение, у которого вызывается метод equals будет равно null, то получим NPE. Проверьте во всем коде, как вызывается метод equals.

2023-07-15 17:25 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/event/service/EventPublicService.java
> +    List<EventShortDto> getAll(String text,
Если в метод нужно передать много параметров, то лучше сделать объект, в который положить все эти параметры. И тогда в метод нужно будет передать только один этот объект. Плюс если добавится еще один параметр, который нужно будет передать в метод, то нужно будет добавить поле в класс. Сигнатура метода при этом не изменится. Не настаиваю на этом изменении, на ваше усмотрение.

2023-07-15 17:25 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/eventrequest/service/EventRequestServiceImpl.java
> +        if (event.getState().getId() != 2) {
Из кода не понятно, что значит в данном месте число 2. Нужно сделать в форме константы с информативным названием.

2023-07-15 17:25 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/util/CommonService.java
> +        }
default

2023-07-16 19:20 UTC, a-sheryshov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/util/CommonService.java
> +        }
fixed

2023-07-17 08:38 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/event/service/EventPublicService.java
> +    List<EventShortDto> getAll(String text,
В данном случае можно было назвать не parameter, а query. Есть два устоявшихся слова для обозначения классов запросовов: query, подходит в данном случае, так как это не мутирующий запрос. А для мутирующих запросов можно называть command.

2023-07-17 08:39 UTC, sergeymamonov approved these changes

2023-07-17 09:23 UTC, a-sheryshov commented on ewm-service/src/main/java/ru/practicum/ewm/mainservice/event/service/EventPublicService.java
> +    List<EventShortDto> getAll(String text,
спасибо, поправлю

2023-07-17 09:52 UTC, a-sheryshov commented
main_svc

2023-07-17 09:52 UTC, merged